//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TGCTDPT.BSNL_SMS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SMS_BSNLSoap", Namespace="http://tempuri.org/")]
    public partial class SMS_BSNL : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Send_Transfers_SMS_bulkOperationCompleted;
        
        private System.Threading.SendOrPostCallback Send_Transfers_SMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback Send_Mbl_Defaulters_SMS_bulkOperationCompleted;
        
        private System.Threading.SendOrPostCallback Send_MBL_Defaulter_SMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_TokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Token_statusOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_content_templateOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_template_variablesOperationCompleted;
        
        private System.Threading.SendOrPostCallback Template_variables_name_changeOperationCompleted;
        
        private System.Threading.SendOrPostCallback Send_sms_format_reqOperationCompleted;
        
        private System.Threading.SendOrPostCallback Send_sms_itcOperationCompleted;
        
        private System.Threading.SendOrPostCallback Send_sms_OTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback ARM_SMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback VATIS_User_OTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback WayBill_Login_credentialsOperationCompleted;
        
        private System.Threading.SendOrPostCallback WayBill_regstration_smsOperationCompleted;
        
        private System.Threading.SendOrPostCallback WayBill_Reset_smsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Send_R3B_SMsOperationCompleted;
        
        private System.Threading.SendOrPostCallback R3B_Bulk_smsOperationCompleted;
        
        private System.Threading.SendOrPostCallback R3B_Bulk_sms_2OperationCompleted;
        
        private System.Threading.SendOrPostCallback Send_Empanelment_MsgOperationCompleted;
        
        private System.Threading.SendOrPostCallback Send_C_Form_Login_OTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback Track_Reports_Dashboard_Login_OTPOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SMS_BSNL() {
            this.Url = global::TGCTDPT.Properties.Settings.Default.TGCTDPT_BSNL_SMS_SMS_BSNL;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Send_Transfers_SMS_bulkCompletedEventHandler Send_Transfers_SMS_bulkCompleted;
        
        /// <remarks/>
        public event Send_Transfers_SMSCompletedEventHandler Send_Transfers_SMSCompleted;
        
        /// <remarks/>
        public event Send_Mbl_Defaulters_SMS_bulkCompletedEventHandler Send_Mbl_Defaulters_SMS_bulkCompleted;
        
        /// <remarks/>
        public event Send_MBL_Defaulter_SMSCompletedEventHandler Send_MBL_Defaulter_SMSCompleted;
        
        /// <remarks/>
        public event Get_TokenCompletedEventHandler Get_TokenCompleted;
        
        /// <remarks/>
        public event Get_Token_statusCompletedEventHandler Get_Token_statusCompleted;
        
        /// <remarks/>
        public event Get_content_templateCompletedEventHandler Get_content_templateCompleted;
        
        /// <remarks/>
        public event Get_template_variablesCompletedEventHandler Get_template_variablesCompleted;
        
        /// <remarks/>
        public event Template_variables_name_changeCompletedEventHandler Template_variables_name_changeCompleted;
        
        /// <remarks/>
        public event Send_sms_format_reqCompletedEventHandler Send_sms_format_reqCompleted;
        
        /// <remarks/>
        public event Send_sms_itcCompletedEventHandler Send_sms_itcCompleted;
        
        /// <remarks/>
        public event Send_sms_OTPCompletedEventHandler Send_sms_OTPCompleted;
        
        /// <remarks/>
        public event ARM_SMSCompletedEventHandler ARM_SMSCompleted;
        
        /// <remarks/>
        public event VATIS_User_OTPCompletedEventHandler VATIS_User_OTPCompleted;
        
        /// <remarks/>
        public event WayBill_Login_credentialsCompletedEventHandler WayBill_Login_credentialsCompleted;
        
        /// <remarks/>
        public event WayBill_regstration_smsCompletedEventHandler WayBill_regstration_smsCompleted;
        
        /// <remarks/>
        public event WayBill_Reset_smsCompletedEventHandler WayBill_Reset_smsCompleted;
        
        /// <remarks/>
        public event Send_R3B_SMsCompletedEventHandler Send_R3B_SMsCompleted;
        
        /// <remarks/>
        public event R3B_Bulk_smsCompletedEventHandler R3B_Bulk_smsCompleted;
        
        /// <remarks/>
        public event R3B_Bulk_sms_2CompletedEventHandler R3B_Bulk_sms_2Completed;
        
        /// <remarks/>
        public event Send_Empanelment_MsgCompletedEventHandler Send_Empanelment_MsgCompleted;
        
        /// <remarks/>
        public event Send_C_Form_Login_OTPCompletedEventHandler Send_C_Form_Login_OTPCompleted;
        
        /// <remarks/>
        public event Track_Reports_Dashboard_Login_OTPCompletedEventHandler Track_Reports_Dashboard_Login_OTPCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Send_Transfers_SMS_bulk", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Send_Transfers_SMS_bulk() {
            this.Invoke("Send_Transfers_SMS_bulk", new object[0]);
        }
        
        /// <remarks/>
        public void Send_Transfers_SMS_bulkAsync() {
            this.Send_Transfers_SMS_bulkAsync(null);
        }
        
        /// <remarks/>
        public void Send_Transfers_SMS_bulkAsync(object userState) {
            if ((this.Send_Transfers_SMS_bulkOperationCompleted == null)) {
                this.Send_Transfers_SMS_bulkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_Transfers_SMS_bulkOperationCompleted);
            }
            this.InvokeAsync("Send_Transfers_SMS_bulk", new object[0], this.Send_Transfers_SMS_bulkOperationCompleted, userState);
        }
        
        private void OnSend_Transfers_SMS_bulkOperationCompleted(object arg) {
            if ((this.Send_Transfers_SMS_bulkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Send_Transfers_SMS_bulkCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Send_Transfers_SMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Send_Transfers_SMS(string mobile) {
            object[] results = this.Invoke("Send_Transfers_SMS", new object[] {
                        mobile});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Send_Transfers_SMSAsync(string mobile) {
            this.Send_Transfers_SMSAsync(mobile, null);
        }
        
        /// <remarks/>
        public void Send_Transfers_SMSAsync(string mobile, object userState) {
            if ((this.Send_Transfers_SMSOperationCompleted == null)) {
                this.Send_Transfers_SMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_Transfers_SMSOperationCompleted);
            }
            this.InvokeAsync("Send_Transfers_SMS", new object[] {
                        mobile}, this.Send_Transfers_SMSOperationCompleted, userState);
        }
        
        private void OnSend_Transfers_SMSOperationCompleted(object arg) {
            if ((this.Send_Transfers_SMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Send_Transfers_SMSCompleted(this, new Send_Transfers_SMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Send_Mbl_Defaulters_SMS_bulk", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Send_Mbl_Defaulters_SMS_bulk() {
            this.Invoke("Send_Mbl_Defaulters_SMS_bulk", new object[0]);
        }
        
        /// <remarks/>
        public void Send_Mbl_Defaulters_SMS_bulkAsync() {
            this.Send_Mbl_Defaulters_SMS_bulkAsync(null);
        }
        
        /// <remarks/>
        public void Send_Mbl_Defaulters_SMS_bulkAsync(object userState) {
            if ((this.Send_Mbl_Defaulters_SMS_bulkOperationCompleted == null)) {
                this.Send_Mbl_Defaulters_SMS_bulkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_Mbl_Defaulters_SMS_bulkOperationCompleted);
            }
            this.InvokeAsync("Send_Mbl_Defaulters_SMS_bulk", new object[0], this.Send_Mbl_Defaulters_SMS_bulkOperationCompleted, userState);
        }
        
        private void OnSend_Mbl_Defaulters_SMS_bulkOperationCompleted(object arg) {
            if ((this.Send_Mbl_Defaulters_SMS_bulkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Send_Mbl_Defaulters_SMS_bulkCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Send_MBL_Defaulter_SMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Send_MBL_Defaulter_SMS(string mobile) {
            object[] results = this.Invoke("Send_MBL_Defaulter_SMS", new object[] {
                        mobile});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Send_MBL_Defaulter_SMSAsync(string mobile) {
            this.Send_MBL_Defaulter_SMSAsync(mobile, null);
        }
        
        /// <remarks/>
        public void Send_MBL_Defaulter_SMSAsync(string mobile, object userState) {
            if ((this.Send_MBL_Defaulter_SMSOperationCompleted == null)) {
                this.Send_MBL_Defaulter_SMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_MBL_Defaulter_SMSOperationCompleted);
            }
            this.InvokeAsync("Send_MBL_Defaulter_SMS", new object[] {
                        mobile}, this.Send_MBL_Defaulter_SMSOperationCompleted, userState);
        }
        
        private void OnSend_MBL_Defaulter_SMSOperationCompleted(object arg) {
            if ((this.Send_MBL_Defaulter_SMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Send_MBL_Defaulter_SMSCompleted(this, new Send_MBL_Defaulter_SMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Token", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_Token() {
            object[] results = this.Invoke("Get_Token", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_TokenAsync() {
            this.Get_TokenAsync(null);
        }
        
        /// <remarks/>
        public void Get_TokenAsync(object userState) {
            if ((this.Get_TokenOperationCompleted == null)) {
                this.Get_TokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_TokenOperationCompleted);
            }
            this.InvokeAsync("Get_Token", new object[0], this.Get_TokenOperationCompleted, userState);
        }
        
        private void OnGet_TokenOperationCompleted(object arg) {
            if ((this.Get_TokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_TokenCompleted(this, new Get_TokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Token_status", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_Token_status() {
            object[] results = this.Invoke("Get_Token_status", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_Token_statusAsync() {
            this.Get_Token_statusAsync(null);
        }
        
        /// <remarks/>
        public void Get_Token_statusAsync(object userState) {
            if ((this.Get_Token_statusOperationCompleted == null)) {
                this.Get_Token_statusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Token_statusOperationCompleted);
            }
            this.InvokeAsync("Get_Token_status", new object[0], this.Get_Token_statusOperationCompleted, userState);
        }
        
        private void OnGet_Token_statusOperationCompleted(object arg) {
            if ((this.Get_Token_statusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Token_statusCompleted(this, new Get_Token_statusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_content_template", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_content_template(string template_id) {
            object[] results = this.Invoke("Get_content_template", new object[] {
                        template_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_content_templateAsync(string template_id) {
            this.Get_content_templateAsync(template_id, null);
        }
        
        /// <remarks/>
        public void Get_content_templateAsync(string template_id, object userState) {
            if ((this.Get_content_templateOperationCompleted == null)) {
                this.Get_content_templateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_content_templateOperationCompleted);
            }
            this.InvokeAsync("Get_content_template", new object[] {
                        template_id}, this.Get_content_templateOperationCompleted, userState);
        }
        
        private void OnGet_content_templateOperationCompleted(object arg) {
            if ((this.Get_content_templateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_content_templateCompleted(this, new Get_content_templateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_template_variables", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_template_variables(string template_id, string Entity_ID) {
            object[] results = this.Invoke("Get_template_variables", new object[] {
                        template_id,
                        Entity_ID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_template_variablesAsync(string template_id, string Entity_ID) {
            this.Get_template_variablesAsync(template_id, Entity_ID, null);
        }
        
        /// <remarks/>
        public void Get_template_variablesAsync(string template_id, string Entity_ID, object userState) {
            if ((this.Get_template_variablesOperationCompleted == null)) {
                this.Get_template_variablesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_template_variablesOperationCompleted);
            }
            this.InvokeAsync("Get_template_variables", new object[] {
                        template_id,
                        Entity_ID}, this.Get_template_variablesOperationCompleted, userState);
        }
        
        private void OnGet_template_variablesOperationCompleted(object arg) {
            if ((this.Get_template_variablesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_template_variablesCompleted(this, new Get_template_variablesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Template_variables_name_change", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Template_variables_name_change(string template_id, string entity_id) {
            object[] results = this.Invoke("Template_variables_name_change", new object[] {
                        template_id,
                        entity_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Template_variables_name_changeAsync(string template_id, string entity_id) {
            this.Template_variables_name_changeAsync(template_id, entity_id, null);
        }
        
        /// <remarks/>
        public void Template_variables_name_changeAsync(string template_id, string entity_id, object userState) {
            if ((this.Template_variables_name_changeOperationCompleted == null)) {
                this.Template_variables_name_changeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTemplate_variables_name_changeOperationCompleted);
            }
            this.InvokeAsync("Template_variables_name_change", new object[] {
                        template_id,
                        entity_id}, this.Template_variables_name_changeOperationCompleted, userState);
        }
        
        private void OnTemplate_variables_name_changeOperationCompleted(object arg) {
            if ((this.Template_variables_name_changeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Template_variables_name_changeCompleted(this, new Template_variables_name_changeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Send_sms_format_req", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Send_sms_format_req(string template_id) {
            object[] results = this.Invoke("Send_sms_format_req", new object[] {
                        template_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Send_sms_format_reqAsync(string template_id) {
            this.Send_sms_format_reqAsync(template_id, null);
        }
        
        /// <remarks/>
        public void Send_sms_format_reqAsync(string template_id, object userState) {
            if ((this.Send_sms_format_reqOperationCompleted == null)) {
                this.Send_sms_format_reqOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_sms_format_reqOperationCompleted);
            }
            this.InvokeAsync("Send_sms_format_req", new object[] {
                        template_id}, this.Send_sms_format_reqOperationCompleted, userState);
        }
        
        private void OnSend_sms_format_reqOperationCompleted(object arg) {
            if ((this.Send_sms_format_reqCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Send_sms_format_reqCompleted(this, new Send_sms_format_reqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Send_sms_itc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Send_sms_itc(string mobile) {
            object[] results = this.Invoke("Send_sms_itc", new object[] {
                        mobile});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Send_sms_itcAsync(string mobile) {
            this.Send_sms_itcAsync(mobile, null);
        }
        
        /// <remarks/>
        public void Send_sms_itcAsync(string mobile, object userState) {
            if ((this.Send_sms_itcOperationCompleted == null)) {
                this.Send_sms_itcOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_sms_itcOperationCompleted);
            }
            this.InvokeAsync("Send_sms_itc", new object[] {
                        mobile}, this.Send_sms_itcOperationCompleted, userState);
        }
        
        private void OnSend_sms_itcOperationCompleted(object arg) {
            if ((this.Send_sms_itcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Send_sms_itcCompleted(this, new Send_sms_itcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Send_sms_OTP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Send_sms_OTP(string mobile) {
            object[] results = this.Invoke("Send_sms_OTP", new object[] {
                        mobile});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Send_sms_OTPAsync(string mobile) {
            this.Send_sms_OTPAsync(mobile, null);
        }
        
        /// <remarks/>
        public void Send_sms_OTPAsync(string mobile, object userState) {
            if ((this.Send_sms_OTPOperationCompleted == null)) {
                this.Send_sms_OTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_sms_OTPOperationCompleted);
            }
            this.InvokeAsync("Send_sms_OTP", new object[] {
                        mobile}, this.Send_sms_OTPOperationCompleted, userState);
        }
        
        private void OnSend_sms_OTPOperationCompleted(object arg) {
            if ((this.Send_sms_OTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Send_sms_OTPCompleted(this, new Send_sms_OTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ARM_SMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ARM_SMS(string mobile) {
            object[] results = this.Invoke("ARM_SMS", new object[] {
                        mobile});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ARM_SMSAsync(string mobile) {
            this.ARM_SMSAsync(mobile, null);
        }
        
        /// <remarks/>
        public void ARM_SMSAsync(string mobile, object userState) {
            if ((this.ARM_SMSOperationCompleted == null)) {
                this.ARM_SMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnARM_SMSOperationCompleted);
            }
            this.InvokeAsync("ARM_SMS", new object[] {
                        mobile}, this.ARM_SMSOperationCompleted, userState);
        }
        
        private void OnARM_SMSOperationCompleted(object arg) {
            if ((this.ARM_SMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ARM_SMSCompleted(this, new ARM_SMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VATIS_User_OTP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VATIS_User_OTP(string mobile, string otp) {
            object[] results = this.Invoke("VATIS_User_OTP", new object[] {
                        mobile,
                        otp});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VATIS_User_OTPAsync(string mobile, string otp) {
            this.VATIS_User_OTPAsync(mobile, otp, null);
        }
        
        /// <remarks/>
        public void VATIS_User_OTPAsync(string mobile, string otp, object userState) {
            if ((this.VATIS_User_OTPOperationCompleted == null)) {
                this.VATIS_User_OTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVATIS_User_OTPOperationCompleted);
            }
            this.InvokeAsync("VATIS_User_OTP", new object[] {
                        mobile,
                        otp}, this.VATIS_User_OTPOperationCompleted, userState);
        }
        
        private void OnVATIS_User_OTPOperationCompleted(object arg) {
            if ((this.VATIS_User_OTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VATIS_User_OTPCompleted(this, new VATIS_User_OTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WayBill_Login_credentials", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WayBill_Login_credentials(string mobile, string password, string Type, string tin) {
            object[] results = this.Invoke("WayBill_Login_credentials", new object[] {
                        mobile,
                        password,
                        Type,
                        tin});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WayBill_Login_credentialsAsync(string mobile, string password, string Type, string tin) {
            this.WayBill_Login_credentialsAsync(mobile, password, Type, tin, null);
        }
        
        /// <remarks/>
        public void WayBill_Login_credentialsAsync(string mobile, string password, string Type, string tin, object userState) {
            if ((this.WayBill_Login_credentialsOperationCompleted == null)) {
                this.WayBill_Login_credentialsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWayBill_Login_credentialsOperationCompleted);
            }
            this.InvokeAsync("WayBill_Login_credentials", new object[] {
                        mobile,
                        password,
                        Type,
                        tin}, this.WayBill_Login_credentialsOperationCompleted, userState);
        }
        
        private void OnWayBill_Login_credentialsOperationCompleted(object arg) {
            if ((this.WayBill_Login_credentialsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WayBill_Login_credentialsCompleted(this, new WayBill_Login_credentialsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WayBill_regstration_sms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WayBill_regstration_sms(string mobile, string otp) {
            object[] results = this.Invoke("WayBill_regstration_sms", new object[] {
                        mobile,
                        otp});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WayBill_regstration_smsAsync(string mobile, string otp) {
            this.WayBill_regstration_smsAsync(mobile, otp, null);
        }
        
        /// <remarks/>
        public void WayBill_regstration_smsAsync(string mobile, string otp, object userState) {
            if ((this.WayBill_regstration_smsOperationCompleted == null)) {
                this.WayBill_regstration_smsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWayBill_regstration_smsOperationCompleted);
            }
            this.InvokeAsync("WayBill_regstration_sms", new object[] {
                        mobile,
                        otp}, this.WayBill_regstration_smsOperationCompleted, userState);
        }
        
        private void OnWayBill_regstration_smsOperationCompleted(object arg) {
            if ((this.WayBill_regstration_smsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WayBill_regstration_smsCompleted(this, new WayBill_regstration_smsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WayBill_Reset_sms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WayBill_Reset_sms(string mobile, string otp, string type) {
            object[] results = this.Invoke("WayBill_Reset_sms", new object[] {
                        mobile,
                        otp,
                        type});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WayBill_Reset_smsAsync(string mobile, string otp, string type) {
            this.WayBill_Reset_smsAsync(mobile, otp, type, null);
        }
        
        /// <remarks/>
        public void WayBill_Reset_smsAsync(string mobile, string otp, string type, object userState) {
            if ((this.WayBill_Reset_smsOperationCompleted == null)) {
                this.WayBill_Reset_smsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWayBill_Reset_smsOperationCompleted);
            }
            this.InvokeAsync("WayBill_Reset_sms", new object[] {
                        mobile,
                        otp,
                        type}, this.WayBill_Reset_smsOperationCompleted, userState);
        }
        
        private void OnWayBill_Reset_smsOperationCompleted(object arg) {
            if ((this.WayBill_Reset_smsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WayBill_Reset_smsCompleted(this, new WayBill_Reset_smsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Send_R3B_SMs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Send_R3B_SMs() {
            this.Invoke("Send_R3B_SMs", new object[0]);
        }
        
        /// <remarks/>
        public void Send_R3B_SMsAsync() {
            this.Send_R3B_SMsAsync(null);
        }
        
        /// <remarks/>
        public void Send_R3B_SMsAsync(object userState) {
            if ((this.Send_R3B_SMsOperationCompleted == null)) {
                this.Send_R3B_SMsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_R3B_SMsOperationCompleted);
            }
            this.InvokeAsync("Send_R3B_SMs", new object[0], this.Send_R3B_SMsOperationCompleted, userState);
        }
        
        private void OnSend_R3B_SMsOperationCompleted(object arg) {
            if ((this.Send_R3B_SMsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Send_R3B_SMsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/R3B_Bulk_sms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string R3B_Bulk_sms(string mobile, string return_month, string datee) {
            object[] results = this.Invoke("R3B_Bulk_sms", new object[] {
                        mobile,
                        return_month,
                        datee});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void R3B_Bulk_smsAsync(string mobile, string return_month, string datee) {
            this.R3B_Bulk_smsAsync(mobile, return_month, datee, null);
        }
        
        /// <remarks/>
        public void R3B_Bulk_smsAsync(string mobile, string return_month, string datee, object userState) {
            if ((this.R3B_Bulk_smsOperationCompleted == null)) {
                this.R3B_Bulk_smsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnR3B_Bulk_smsOperationCompleted);
            }
            this.InvokeAsync("R3B_Bulk_sms", new object[] {
                        mobile,
                        return_month,
                        datee}, this.R3B_Bulk_smsOperationCompleted, userState);
        }
        
        private void OnR3B_Bulk_smsOperationCompleted(object arg) {
            if ((this.R3B_Bulk_smsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.R3B_Bulk_smsCompleted(this, new R3B_Bulk_smsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/R3B_Bulk_sms_2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string R3B_Bulk_sms_2(string mobile, string return_month, string division) {
            object[] results = this.Invoke("R3B_Bulk_sms_2", new object[] {
                        mobile,
                        return_month,
                        division});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void R3B_Bulk_sms_2Async(string mobile, string return_month, string division) {
            this.R3B_Bulk_sms_2Async(mobile, return_month, division, null);
        }
        
        /// <remarks/>
        public void R3B_Bulk_sms_2Async(string mobile, string return_month, string division, object userState) {
            if ((this.R3B_Bulk_sms_2OperationCompleted == null)) {
                this.R3B_Bulk_sms_2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnR3B_Bulk_sms_2OperationCompleted);
            }
            this.InvokeAsync("R3B_Bulk_sms_2", new object[] {
                        mobile,
                        return_month,
                        division}, this.R3B_Bulk_sms_2OperationCompleted, userState);
        }
        
        private void OnR3B_Bulk_sms_2OperationCompleted(object arg) {
            if ((this.R3B_Bulk_sms_2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.R3B_Bulk_sms_2Completed(this, new R3B_Bulk_sms_2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Send_Empanelment_Msg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Send_Empanelment_Msg(string mobile, string Empn_Id) {
            object[] results = this.Invoke("Send_Empanelment_Msg", new object[] {
                        mobile,
                        Empn_Id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Send_Empanelment_MsgAsync(string mobile, string Empn_Id) {
            this.Send_Empanelment_MsgAsync(mobile, Empn_Id, null);
        }
        
        /// <remarks/>
        public void Send_Empanelment_MsgAsync(string mobile, string Empn_Id, object userState) {
            if ((this.Send_Empanelment_MsgOperationCompleted == null)) {
                this.Send_Empanelment_MsgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_Empanelment_MsgOperationCompleted);
            }
            this.InvokeAsync("Send_Empanelment_Msg", new object[] {
                        mobile,
                        Empn_Id}, this.Send_Empanelment_MsgOperationCompleted, userState);
        }
        
        private void OnSend_Empanelment_MsgOperationCompleted(object arg) {
            if ((this.Send_Empanelment_MsgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Send_Empanelment_MsgCompleted(this, new Send_Empanelment_MsgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Send_C_Form_Login_OTP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Send_C_Form_Login_OTP(string mobile, string otp, string minutes) {
            object[] results = this.Invoke("Send_C_Form_Login_OTP", new object[] {
                        mobile,
                        otp,
                        minutes});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Send_C_Form_Login_OTPAsync(string mobile, string otp, string minutes) {
            this.Send_C_Form_Login_OTPAsync(mobile, otp, minutes, null);
        }
        
        /// <remarks/>
        public void Send_C_Form_Login_OTPAsync(string mobile, string otp, string minutes, object userState) {
            if ((this.Send_C_Form_Login_OTPOperationCompleted == null)) {
                this.Send_C_Form_Login_OTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSend_C_Form_Login_OTPOperationCompleted);
            }
            this.InvokeAsync("Send_C_Form_Login_OTP", new object[] {
                        mobile,
                        otp,
                        minutes}, this.Send_C_Form_Login_OTPOperationCompleted, userState);
        }
        
        private void OnSend_C_Form_Login_OTPOperationCompleted(object arg) {
            if ((this.Send_C_Form_Login_OTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Send_C_Form_Login_OTPCompleted(this, new Send_C_Form_Login_OTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Track_Reports_Dashboard_Login_OTP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Track_Reports_Dashboard_Login_OTP(string mobile, string otp, string minutes) {
            object[] results = this.Invoke("Track_Reports_Dashboard_Login_OTP", new object[] {
                        mobile,
                        otp,
                        minutes});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Track_Reports_Dashboard_Login_OTPAsync(string mobile, string otp, string minutes) {
            this.Track_Reports_Dashboard_Login_OTPAsync(mobile, otp, minutes, null);
        }
        
        /// <remarks/>
        public void Track_Reports_Dashboard_Login_OTPAsync(string mobile, string otp, string minutes, object userState) {
            if ((this.Track_Reports_Dashboard_Login_OTPOperationCompleted == null)) {
                this.Track_Reports_Dashboard_Login_OTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrack_Reports_Dashboard_Login_OTPOperationCompleted);
            }
            this.InvokeAsync("Track_Reports_Dashboard_Login_OTP", new object[] {
                        mobile,
                        otp,
                        minutes}, this.Track_Reports_Dashboard_Login_OTPOperationCompleted, userState);
        }
        
        private void OnTrack_Reports_Dashboard_Login_OTPOperationCompleted(object arg) {
            if ((this.Track_Reports_Dashboard_Login_OTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Track_Reports_Dashboard_Login_OTPCompleted(this, new Track_Reports_Dashboard_Login_OTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Send_Transfers_SMS_bulkCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Send_Transfers_SMSCompletedEventHandler(object sender, Send_Transfers_SMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Send_Transfers_SMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Send_Transfers_SMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Send_Mbl_Defaulters_SMS_bulkCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Send_MBL_Defaulter_SMSCompletedEventHandler(object sender, Send_MBL_Defaulter_SMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Send_MBL_Defaulter_SMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Send_MBL_Defaulter_SMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Get_TokenCompletedEventHandler(object sender, Get_TokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_TokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_TokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Get_Token_statusCompletedEventHandler(object sender, Get_Token_statusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Token_statusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Token_statusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Get_content_templateCompletedEventHandler(object sender, Get_content_templateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_content_templateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_content_templateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Get_template_variablesCompletedEventHandler(object sender, Get_template_variablesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_template_variablesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_template_variablesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Template_variables_name_changeCompletedEventHandler(object sender, Template_variables_name_changeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Template_variables_name_changeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Template_variables_name_changeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Send_sms_format_reqCompletedEventHandler(object sender, Send_sms_format_reqCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Send_sms_format_reqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Send_sms_format_reqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Send_sms_itcCompletedEventHandler(object sender, Send_sms_itcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Send_sms_itcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Send_sms_itcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Send_sms_OTPCompletedEventHandler(object sender, Send_sms_OTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Send_sms_OTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Send_sms_OTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ARM_SMSCompletedEventHandler(object sender, ARM_SMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ARM_SMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ARM_SMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void VATIS_User_OTPCompletedEventHandler(object sender, VATIS_User_OTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VATIS_User_OTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VATIS_User_OTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WayBill_Login_credentialsCompletedEventHandler(object sender, WayBill_Login_credentialsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WayBill_Login_credentialsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WayBill_Login_credentialsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WayBill_regstration_smsCompletedEventHandler(object sender, WayBill_regstration_smsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WayBill_regstration_smsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WayBill_regstration_smsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WayBill_Reset_smsCompletedEventHandler(object sender, WayBill_Reset_smsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WayBill_Reset_smsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WayBill_Reset_smsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Send_R3B_SMsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void R3B_Bulk_smsCompletedEventHandler(object sender, R3B_Bulk_smsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class R3B_Bulk_smsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal R3B_Bulk_smsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void R3B_Bulk_sms_2CompletedEventHandler(object sender, R3B_Bulk_sms_2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class R3B_Bulk_sms_2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal R3B_Bulk_sms_2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Send_Empanelment_MsgCompletedEventHandler(object sender, Send_Empanelment_MsgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Send_Empanelment_MsgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Send_Empanelment_MsgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Send_C_Form_Login_OTPCompletedEventHandler(object sender, Send_C_Form_Login_OTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Send_C_Form_Login_OTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Send_C_Form_Login_OTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Track_Reports_Dashboard_Login_OTPCompletedEventHandler(object sender, Track_Reports_Dashboard_Login_OTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Track_Reports_Dashboard_Login_OTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Track_Reports_Dashboard_Login_OTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591