//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TGCTDPT.Mail_Services {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="send_mailSoap", Namespace="http://tempuri.org/")]
    public partial class send_mail : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Auto_mail_live_test2OperationCompleted;
        
        private System.Threading.SendOrPostCallback Auto_mailOperationCompleted;
        
        private System.Threading.SendOrPostCallback ITC_circular_09112022OperationCompleted;
        
        private System.Threading.SendOrPostCallback PT_mail_Not_paid_list_AutoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GSTR9c_mailOperationCompleted;
        
        private System.Threading.SendOrPostCallback PT_mail_Not_paid_listOperationCompleted;
        
        private System.Threading.SendOrPostCallback Live_mail_Bulk_for_RupaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Live_mail_BulkOperationCompleted;
        
        private System.Threading.SendOrPostCallback PT_auto_gen_SendmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback send_mail_daily_reportOperationCompleted;
        
        private System.Threading.SendOrPostCallback send_mail_appOperationCompleted;
        
        private System.Threading.SendOrPostCallback send_mail_ptin_appOperationCompleted;
        
        private System.Threading.SendOrPostCallback send_mail_Vat_reset_passwordOperationCompleted;
        
        private System.Threading.SendOrPostCallback send_mail_Vat_Registration_OTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback send_mail_PT_GST_new_usersOperationCompleted;
        
        private System.Threading.SendOrPostCallback send_mail_statusOperationCompleted;
        
        private System.Threading.SendOrPostCallback Auto_mail_liveOperationCompleted;
        
        private System.Threading.SendOrPostCallback GST_payment_report_dateWiseOperationCompleted;
        
        private System.Threading.SendOrPostCallback test_mail_liveOperationCompleted;
        
        private System.Threading.SendOrPostCallback test_mailOperationCompleted;
        
        private System.Threading.SendOrPostCallback getpr_mail_service_sent_statusOperationCompleted;
        
        private System.Threading.SendOrPostCallback PT_Send_Application_ApprovedOperationCompleted;
        
        private System.Threading.SendOrPostCallback PT_Send_Reset_PasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback PT_Send_ARN_NumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback PT_Send_Application_NumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback PT_Return_Reminder_mailOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public send_mail() {
            this.Url = global::TGCTDPT.Properties.Settings.Default.TGCTDPT_Mail_Services_send_mail;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Auto_mail_live_test2CompletedEventHandler Auto_mail_live_test2Completed;
        
        /// <remarks/>
        public event Auto_mailCompletedEventHandler Auto_mailCompleted;
        
        /// <remarks/>
        public event ITC_circular_09112022CompletedEventHandler ITC_circular_09112022Completed;
        
        /// <remarks/>
        public event PT_mail_Not_paid_list_AutoCompletedEventHandler PT_mail_Not_paid_list_AutoCompleted;
        
        /// <remarks/>
        public event GSTR9c_mailCompletedEventHandler GSTR9c_mailCompleted;
        
        /// <remarks/>
        public event PT_mail_Not_paid_listCompletedEventHandler PT_mail_Not_paid_listCompleted;
        
        /// <remarks/>
        public event Live_mail_Bulk_for_RupaCompletedEventHandler Live_mail_Bulk_for_RupaCompleted;
        
        /// <remarks/>
        public event Live_mail_BulkCompletedEventHandler Live_mail_BulkCompleted;
        
        /// <remarks/>
        public event PT_auto_gen_SendmailCompletedEventHandler PT_auto_gen_SendmailCompleted;
        
        /// <remarks/>
        public event send_mail_daily_reportCompletedEventHandler send_mail_daily_reportCompleted;
        
        /// <remarks/>
        public event send_mail_appCompletedEventHandler send_mail_appCompleted;
        
        /// <remarks/>
        public event send_mail_ptin_appCompletedEventHandler send_mail_ptin_appCompleted;
        
        /// <remarks/>
        public event send_mail_Vat_reset_passwordCompletedEventHandler send_mail_Vat_reset_passwordCompleted;
        
        /// <remarks/>
        public event send_mail_Vat_Registration_OTPCompletedEventHandler send_mail_Vat_Registration_OTPCompleted;
        
        /// <remarks/>
        public event send_mail_PT_GST_new_usersCompletedEventHandler send_mail_PT_GST_new_usersCompleted;
        
        /// <remarks/>
        public event send_mail_statusCompletedEventHandler send_mail_statusCompleted;
        
        /// <remarks/>
        public event Auto_mail_liveCompletedEventHandler Auto_mail_liveCompleted;
        
        /// <remarks/>
        public event GST_payment_report_dateWiseCompletedEventHandler GST_payment_report_dateWiseCompleted;
        
        /// <remarks/>
        public event test_mail_liveCompletedEventHandler test_mail_liveCompleted;
        
        /// <remarks/>
        public event test_mailCompletedEventHandler test_mailCompleted;
        
        /// <remarks/>
        public event getpr_mail_service_sent_statusCompletedEventHandler getpr_mail_service_sent_statusCompleted;
        
        /// <remarks/>
        public event PT_Send_Application_ApprovedCompletedEventHandler PT_Send_Application_ApprovedCompleted;
        
        /// <remarks/>
        public event PT_Send_Reset_PasswordCompletedEventHandler PT_Send_Reset_PasswordCompleted;
        
        /// <remarks/>
        public event PT_Send_ARN_NumberCompletedEventHandler PT_Send_ARN_NumberCompleted;
        
        /// <remarks/>
        public event PT_Send_Application_NumberCompletedEventHandler PT_Send_Application_NumberCompleted;
        
        /// <remarks/>
        public event PT_Return_Reminder_mailCompletedEventHandler PT_Return_Reminder_mailCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Auto_mail_live_test2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Auto_mail_live_test2(string mailid, string ccmailid, string type, string bccmailid) {
            object[] results = this.Invoke("Auto_mail_live_test2", new object[] {
                        mailid,
                        ccmailid,
                        type,
                        bccmailid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Auto_mail_live_test2Async(string mailid, string ccmailid, string type, string bccmailid) {
            this.Auto_mail_live_test2Async(mailid, ccmailid, type, bccmailid, null);
        }
        
        /// <remarks/>
        public void Auto_mail_live_test2Async(string mailid, string ccmailid, string type, string bccmailid, object userState) {
            if ((this.Auto_mail_live_test2OperationCompleted == null)) {
                this.Auto_mail_live_test2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuto_mail_live_test2OperationCompleted);
            }
            this.InvokeAsync("Auto_mail_live_test2", new object[] {
                        mailid,
                        ccmailid,
                        type,
                        bccmailid}, this.Auto_mail_live_test2OperationCompleted, userState);
        }
        
        private void OnAuto_mail_live_test2OperationCompleted(object arg) {
            if ((this.Auto_mail_live_test2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Auto_mail_live_test2Completed(this, new Auto_mail_live_test2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Auto_mail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Auto_mail(string mailid, string ccmailid, string type, string bccmailid) {
            object[] results = this.Invoke("Auto_mail", new object[] {
                        mailid,
                        ccmailid,
                        type,
                        bccmailid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Auto_mailAsync(string mailid, string ccmailid, string type, string bccmailid) {
            this.Auto_mailAsync(mailid, ccmailid, type, bccmailid, null);
        }
        
        /// <remarks/>
        public void Auto_mailAsync(string mailid, string ccmailid, string type, string bccmailid, object userState) {
            if ((this.Auto_mailOperationCompleted == null)) {
                this.Auto_mailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuto_mailOperationCompleted);
            }
            this.InvokeAsync("Auto_mail", new object[] {
                        mailid,
                        ccmailid,
                        type,
                        bccmailid}, this.Auto_mailOperationCompleted, userState);
        }
        
        private void OnAuto_mailOperationCompleted(object arg) {
            if ((this.Auto_mailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Auto_mailCompleted(this, new Auto_mailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITC_circular_09112022", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ITC_circular_09112022(string mailid) {
            object[] results = this.Invoke("ITC_circular_09112022", new object[] {
                        mailid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ITC_circular_09112022Async(string mailid) {
            this.ITC_circular_09112022Async(mailid, null);
        }
        
        /// <remarks/>
        public void ITC_circular_09112022Async(string mailid, object userState) {
            if ((this.ITC_circular_09112022OperationCompleted == null)) {
                this.ITC_circular_09112022OperationCompleted = new System.Threading.SendOrPostCallback(this.OnITC_circular_09112022OperationCompleted);
            }
            this.InvokeAsync("ITC_circular_09112022", new object[] {
                        mailid}, this.ITC_circular_09112022OperationCompleted, userState);
        }
        
        private void OnITC_circular_09112022OperationCompleted(object arg) {
            if ((this.ITC_circular_09112022Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ITC_circular_09112022Completed(this, new ITC_circular_09112022CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PT_mail_Not_paid_list_Auto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PT_mail_Not_paid_list_Auto() {
            this.Invoke("PT_mail_Not_paid_list_Auto", new object[0]);
        }
        
        /// <remarks/>
        public void PT_mail_Not_paid_list_AutoAsync() {
            this.PT_mail_Not_paid_list_AutoAsync(null);
        }
        
        /// <remarks/>
        public void PT_mail_Not_paid_list_AutoAsync(object userState) {
            if ((this.PT_mail_Not_paid_list_AutoOperationCompleted == null)) {
                this.PT_mail_Not_paid_list_AutoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPT_mail_Not_paid_list_AutoOperationCompleted);
            }
            this.InvokeAsync("PT_mail_Not_paid_list_Auto", new object[0], this.PT_mail_Not_paid_list_AutoOperationCompleted, userState);
        }
        
        private void OnPT_mail_Not_paid_list_AutoOperationCompleted(object arg) {
            if ((this.PT_mail_Not_paid_list_AutoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PT_mail_Not_paid_list_AutoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GSTR9c_mail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GSTR9c_mail() {
            this.Invoke("GSTR9c_mail", new object[0]);
        }
        
        /// <remarks/>
        public void GSTR9c_mailAsync() {
            this.GSTR9c_mailAsync(null);
        }
        
        /// <remarks/>
        public void GSTR9c_mailAsync(object userState) {
            if ((this.GSTR9c_mailOperationCompleted == null)) {
                this.GSTR9c_mailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGSTR9c_mailOperationCompleted);
            }
            this.InvokeAsync("GSTR9c_mail", new object[0], this.GSTR9c_mailOperationCompleted, userState);
        }
        
        private void OnGSTR9c_mailOperationCompleted(object arg) {
            if ((this.GSTR9c_mailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GSTR9c_mailCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PT_mail_Not_paid_list", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PT_mail_Not_paid_list(string mailid, string ptin, string name, string circle) {
            object[] results = this.Invoke("PT_mail_Not_paid_list", new object[] {
                        mailid,
                        ptin,
                        name,
                        circle});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PT_mail_Not_paid_listAsync(string mailid, string ptin, string name, string circle) {
            this.PT_mail_Not_paid_listAsync(mailid, ptin, name, circle, null);
        }
        
        /// <remarks/>
        public void PT_mail_Not_paid_listAsync(string mailid, string ptin, string name, string circle, object userState) {
            if ((this.PT_mail_Not_paid_listOperationCompleted == null)) {
                this.PT_mail_Not_paid_listOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPT_mail_Not_paid_listOperationCompleted);
            }
            this.InvokeAsync("PT_mail_Not_paid_list", new object[] {
                        mailid,
                        ptin,
                        name,
                        circle}, this.PT_mail_Not_paid_listOperationCompleted, userState);
        }
        
        private void OnPT_mail_Not_paid_listOperationCompleted(object arg) {
            if ((this.PT_mail_Not_paid_listCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PT_mail_Not_paid_listCompleted(this, new PT_mail_Not_paid_listCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Live_mail_Bulk_for_Rupa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Live_mail_Bulk_for_Rupa(string mailid, string ccmailid, string bccmailid, string attachment_path) {
            object[] results = this.Invoke("Live_mail_Bulk_for_Rupa", new object[] {
                        mailid,
                        ccmailid,
                        bccmailid,
                        attachment_path});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Live_mail_Bulk_for_RupaAsync(string mailid, string ccmailid, string bccmailid, string attachment_path) {
            this.Live_mail_Bulk_for_RupaAsync(mailid, ccmailid, bccmailid, attachment_path, null);
        }
        
        /// <remarks/>
        public void Live_mail_Bulk_for_RupaAsync(string mailid, string ccmailid, string bccmailid, string attachment_path, object userState) {
            if ((this.Live_mail_Bulk_for_RupaOperationCompleted == null)) {
                this.Live_mail_Bulk_for_RupaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLive_mail_Bulk_for_RupaOperationCompleted);
            }
            this.InvokeAsync("Live_mail_Bulk_for_Rupa", new object[] {
                        mailid,
                        ccmailid,
                        bccmailid,
                        attachment_path}, this.Live_mail_Bulk_for_RupaOperationCompleted, userState);
        }
        
        private void OnLive_mail_Bulk_for_RupaOperationCompleted(object arg) {
            if ((this.Live_mail_Bulk_for_RupaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Live_mail_Bulk_for_RupaCompleted(this, new Live_mail_Bulk_for_RupaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Live_mail_Bulk", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Live_mail_Bulk(string mailid, string ccmailid, string bccmailid, string attachment_path, string gstin, string legalname) {
            object[] results = this.Invoke("Live_mail_Bulk", new object[] {
                        mailid,
                        ccmailid,
                        bccmailid,
                        attachment_path,
                        gstin,
                        legalname});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Live_mail_BulkAsync(string mailid, string ccmailid, string bccmailid, string attachment_path, string gstin, string legalname) {
            this.Live_mail_BulkAsync(mailid, ccmailid, bccmailid, attachment_path, gstin, legalname, null);
        }
        
        /// <remarks/>
        public void Live_mail_BulkAsync(string mailid, string ccmailid, string bccmailid, string attachment_path, string gstin, string legalname, object userState) {
            if ((this.Live_mail_BulkOperationCompleted == null)) {
                this.Live_mail_BulkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLive_mail_BulkOperationCompleted);
            }
            this.InvokeAsync("Live_mail_Bulk", new object[] {
                        mailid,
                        ccmailid,
                        bccmailid,
                        attachment_path,
                        gstin,
                        legalname}, this.Live_mail_BulkOperationCompleted, userState);
        }
        
        private void OnLive_mail_BulkOperationCompleted(object arg) {
            if ((this.Live_mail_BulkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Live_mail_BulkCompleted(this, new Live_mail_BulkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PT_auto_gen_Sendmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PT_auto_gen_Sendmail(string ptin, string password, string mailid) {
            object[] results = this.Invoke("PT_auto_gen_Sendmail", new object[] {
                        ptin,
                        password,
                        mailid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PT_auto_gen_SendmailAsync(string ptin, string password, string mailid) {
            this.PT_auto_gen_SendmailAsync(ptin, password, mailid, null);
        }
        
        /// <remarks/>
        public void PT_auto_gen_SendmailAsync(string ptin, string password, string mailid, object userState) {
            if ((this.PT_auto_gen_SendmailOperationCompleted == null)) {
                this.PT_auto_gen_SendmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPT_auto_gen_SendmailOperationCompleted);
            }
            this.InvokeAsync("PT_auto_gen_Sendmail", new object[] {
                        ptin,
                        password,
                        mailid}, this.PT_auto_gen_SendmailOperationCompleted, userState);
        }
        
        private void OnPT_auto_gen_SendmailOperationCompleted(object arg) {
            if ((this.PT_auto_gen_SendmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PT_auto_gen_SendmailCompleted(this, new PT_auto_gen_SendmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/send_mail_daily_report", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool send_mail_daily_report(string from_mail, string from_pass, string tomail, string cc, string sub, string body, string attachment) {
            object[] results = this.Invoke("send_mail_daily_report", new object[] {
                        from_mail,
                        from_pass,
                        tomail,
                        cc,
                        sub,
                        body,
                        attachment});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void send_mail_daily_reportAsync(string from_mail, string from_pass, string tomail, string cc, string sub, string body, string attachment) {
            this.send_mail_daily_reportAsync(from_mail, from_pass, tomail, cc, sub, body, attachment, null);
        }
        
        /// <remarks/>
        public void send_mail_daily_reportAsync(string from_mail, string from_pass, string tomail, string cc, string sub, string body, string attachment, object userState) {
            if ((this.send_mail_daily_reportOperationCompleted == null)) {
                this.send_mail_daily_reportOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsend_mail_daily_reportOperationCompleted);
            }
            this.InvokeAsync("send_mail_daily_report", new object[] {
                        from_mail,
                        from_pass,
                        tomail,
                        cc,
                        sub,
                        body,
                        attachment}, this.send_mail_daily_reportOperationCompleted, userState);
        }
        
        private void Onsend_mail_daily_reportOperationCompleted(object arg) {
            if ((this.send_mail_daily_reportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.send_mail_daily_reportCompleted(this, new send_mail_daily_reportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/send_mail_app", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool send_mail_app(string email, string pwd) {
            object[] results = this.Invoke("send_mail_app", new object[] {
                        email,
                        pwd});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void send_mail_appAsync(string email, string pwd) {
            this.send_mail_appAsync(email, pwd, null);
        }
        
        /// <remarks/>
        public void send_mail_appAsync(string email, string pwd, object userState) {
            if ((this.send_mail_appOperationCompleted == null)) {
                this.send_mail_appOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsend_mail_appOperationCompleted);
            }
            this.InvokeAsync("send_mail_app", new object[] {
                        email,
                        pwd}, this.send_mail_appOperationCompleted, userState);
        }
        
        private void Onsend_mail_appOperationCompleted(object arg) {
            if ((this.send_mail_appCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.send_mail_appCompleted(this, new send_mail_appCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/send_mail_ptin_app", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool send_mail_ptin_app(string email, string pwd, string ptin) {
            object[] results = this.Invoke("send_mail_ptin_app", new object[] {
                        email,
                        pwd,
                        ptin});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void send_mail_ptin_appAsync(string email, string pwd, string ptin) {
            this.send_mail_ptin_appAsync(email, pwd, ptin, null);
        }
        
        /// <remarks/>
        public void send_mail_ptin_appAsync(string email, string pwd, string ptin, object userState) {
            if ((this.send_mail_ptin_appOperationCompleted == null)) {
                this.send_mail_ptin_appOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsend_mail_ptin_appOperationCompleted);
            }
            this.InvokeAsync("send_mail_ptin_app", new object[] {
                        email,
                        pwd,
                        ptin}, this.send_mail_ptin_appOperationCompleted, userState);
        }
        
        private void Onsend_mail_ptin_appOperationCompleted(object arg) {
            if ((this.send_mail_ptin_appCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.send_mail_ptin_appCompleted(this, new send_mail_ptin_appCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/send_mail_Vat_reset_password", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool send_mail_Vat_reset_password(string email, string pwd, string TIN) {
            object[] results = this.Invoke("send_mail_Vat_reset_password", new object[] {
                        email,
                        pwd,
                        TIN});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void send_mail_Vat_reset_passwordAsync(string email, string pwd, string TIN) {
            this.send_mail_Vat_reset_passwordAsync(email, pwd, TIN, null);
        }
        
        /// <remarks/>
        public void send_mail_Vat_reset_passwordAsync(string email, string pwd, string TIN, object userState) {
            if ((this.send_mail_Vat_reset_passwordOperationCompleted == null)) {
                this.send_mail_Vat_reset_passwordOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsend_mail_Vat_reset_passwordOperationCompleted);
            }
            this.InvokeAsync("send_mail_Vat_reset_password", new object[] {
                        email,
                        pwd,
                        TIN}, this.send_mail_Vat_reset_passwordOperationCompleted, userState);
        }
        
        private void Onsend_mail_Vat_reset_passwordOperationCompleted(object arg) {
            if ((this.send_mail_Vat_reset_passwordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.send_mail_Vat_reset_passwordCompleted(this, new send_mail_Vat_reset_passwordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/send_mail_Vat_Registration_OTP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool send_mail_Vat_Registration_OTP(string email, string pwd) {
            object[] results = this.Invoke("send_mail_Vat_Registration_OTP", new object[] {
                        email,
                        pwd});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void send_mail_Vat_Registration_OTPAsync(string email, string pwd) {
            this.send_mail_Vat_Registration_OTPAsync(email, pwd, null);
        }
        
        /// <remarks/>
        public void send_mail_Vat_Registration_OTPAsync(string email, string pwd, object userState) {
            if ((this.send_mail_Vat_Registration_OTPOperationCompleted == null)) {
                this.send_mail_Vat_Registration_OTPOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsend_mail_Vat_Registration_OTPOperationCompleted);
            }
            this.InvokeAsync("send_mail_Vat_Registration_OTP", new object[] {
                        email,
                        pwd}, this.send_mail_Vat_Registration_OTPOperationCompleted, userState);
        }
        
        private void Onsend_mail_Vat_Registration_OTPOperationCompleted(object arg) {
            if ((this.send_mail_Vat_Registration_OTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.send_mail_Vat_Registration_OTPCompleted(this, new send_mail_Vat_Registration_OTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/send_mail_PT_GST_new_users", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string send_mail_PT_GST_new_users(string part) {
            object[] results = this.Invoke("send_mail_PT_GST_new_users", new object[] {
                        part});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void send_mail_PT_GST_new_usersAsync(string part) {
            this.send_mail_PT_GST_new_usersAsync(part, null);
        }
        
        /// <remarks/>
        public void send_mail_PT_GST_new_usersAsync(string part, object userState) {
            if ((this.send_mail_PT_GST_new_usersOperationCompleted == null)) {
                this.send_mail_PT_GST_new_usersOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsend_mail_PT_GST_new_usersOperationCompleted);
            }
            this.InvokeAsync("send_mail_PT_GST_new_users", new object[] {
                        part}, this.send_mail_PT_GST_new_usersOperationCompleted, userState);
        }
        
        private void Onsend_mail_PT_GST_new_usersOperationCompleted(object arg) {
            if ((this.send_mail_PT_GST_new_usersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.send_mail_PT_GST_new_usersCompleted(this, new send_mail_PT_GST_new_usersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/send_mail_status", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string send_mail_status() {
            object[] results = this.Invoke("send_mail_status", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void send_mail_statusAsync() {
            this.send_mail_statusAsync(null);
        }
        
        /// <remarks/>
        public void send_mail_statusAsync(object userState) {
            if ((this.send_mail_statusOperationCompleted == null)) {
                this.send_mail_statusOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsend_mail_statusOperationCompleted);
            }
            this.InvokeAsync("send_mail_status", new object[0], this.send_mail_statusOperationCompleted, userState);
        }
        
        private void Onsend_mail_statusOperationCompleted(object arg) {
            if ((this.send_mail_statusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.send_mail_statusCompleted(this, new send_mail_statusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Auto_mail_live", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Auto_mail_live(string mailid, string ccmailid, string type, string bccmailid) {
            object[] results = this.Invoke("Auto_mail_live", new object[] {
                        mailid,
                        ccmailid,
                        type,
                        bccmailid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Auto_mail_liveAsync(string mailid, string ccmailid, string type, string bccmailid) {
            this.Auto_mail_liveAsync(mailid, ccmailid, type, bccmailid, null);
        }
        
        /// <remarks/>
        public void Auto_mail_liveAsync(string mailid, string ccmailid, string type, string bccmailid, object userState) {
            if ((this.Auto_mail_liveOperationCompleted == null)) {
                this.Auto_mail_liveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuto_mail_liveOperationCompleted);
            }
            this.InvokeAsync("Auto_mail_live", new object[] {
                        mailid,
                        ccmailid,
                        type,
                        bccmailid}, this.Auto_mail_liveOperationCompleted, userState);
        }
        
        private void OnAuto_mail_liveOperationCompleted(object arg) {
            if ((this.Auto_mail_liveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Auto_mail_liveCompleted(this, new Auto_mail_liveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GST_payment_report_dateWise", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GST_payment_report_dateWise(string start_date, string enddate) {
            object[] results = this.Invoke("GST_payment_report_dateWise", new object[] {
                        start_date,
                        enddate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GST_payment_report_dateWiseAsync(string start_date, string enddate) {
            this.GST_payment_report_dateWiseAsync(start_date, enddate, null);
        }
        
        /// <remarks/>
        public void GST_payment_report_dateWiseAsync(string start_date, string enddate, object userState) {
            if ((this.GST_payment_report_dateWiseOperationCompleted == null)) {
                this.GST_payment_report_dateWiseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGST_payment_report_dateWiseOperationCompleted);
            }
            this.InvokeAsync("GST_payment_report_dateWise", new object[] {
                        start_date,
                        enddate}, this.GST_payment_report_dateWiseOperationCompleted, userState);
        }
        
        private void OnGST_payment_report_dateWiseOperationCompleted(object arg) {
            if ((this.GST_payment_report_dateWiseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GST_payment_report_dateWiseCompleted(this, new GST_payment_report_dateWiseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/test_mail_live", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string test_mail_live(string mailid, string ccmailid, string type, string bccmailid) {
            object[] results = this.Invoke("test_mail_live", new object[] {
                        mailid,
                        ccmailid,
                        type,
                        bccmailid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void test_mail_liveAsync(string mailid, string ccmailid, string type, string bccmailid) {
            this.test_mail_liveAsync(mailid, ccmailid, type, bccmailid, null);
        }
        
        /// <remarks/>
        public void test_mail_liveAsync(string mailid, string ccmailid, string type, string bccmailid, object userState) {
            if ((this.test_mail_liveOperationCompleted == null)) {
                this.test_mail_liveOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontest_mail_liveOperationCompleted);
            }
            this.InvokeAsync("test_mail_live", new object[] {
                        mailid,
                        ccmailid,
                        type,
                        bccmailid}, this.test_mail_liveOperationCompleted, userState);
        }
        
        private void Ontest_mail_liveOperationCompleted(object arg) {
            if ((this.test_mail_liveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.test_mail_liveCompleted(this, new test_mail_liveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/test_mail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool test_mail(string mailid, string ccmailid) {
            object[] results = this.Invoke("test_mail", new object[] {
                        mailid,
                        ccmailid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void test_mailAsync(string mailid, string ccmailid) {
            this.test_mailAsync(mailid, ccmailid, null);
        }
        
        /// <remarks/>
        public void test_mailAsync(string mailid, string ccmailid, object userState) {
            if ((this.test_mailOperationCompleted == null)) {
                this.test_mailOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontest_mailOperationCompleted);
            }
            this.InvokeAsync("test_mail", new object[] {
                        mailid,
                        ccmailid}, this.test_mailOperationCompleted, userState);
        }
        
        private void Ontest_mailOperationCompleted(object arg) {
            if ((this.test_mailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.test_mailCompleted(this, new test_mailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getpr_mail_service_sent_status", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getpr_mail_service_sent_status(string flag) {
            object[] results = this.Invoke("getpr_mail_service_sent_status", new object[] {
                        flag});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getpr_mail_service_sent_statusAsync(string flag) {
            this.getpr_mail_service_sent_statusAsync(flag, null);
        }
        
        /// <remarks/>
        public void getpr_mail_service_sent_statusAsync(string flag, object userState) {
            if ((this.getpr_mail_service_sent_statusOperationCompleted == null)) {
                this.getpr_mail_service_sent_statusOperationCompleted = new System.Threading.SendOrPostCallback(this.Ongetpr_mail_service_sent_statusOperationCompleted);
            }
            this.InvokeAsync("getpr_mail_service_sent_status", new object[] {
                        flag}, this.getpr_mail_service_sent_statusOperationCompleted, userState);
        }
        
        private void Ongetpr_mail_service_sent_statusOperationCompleted(object arg) {
            if ((this.getpr_mail_service_sent_statusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getpr_mail_service_sent_statusCompleted(this, new getpr_mail_service_sent_statusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PT_Send_Application_Approved", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PT_Send_Application_Approved(string ptin, string mobile, string mailid) {
            object[] results = this.Invoke("PT_Send_Application_Approved", new object[] {
                        ptin,
                        mobile,
                        mailid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PT_Send_Application_ApprovedAsync(string ptin, string mobile, string mailid) {
            this.PT_Send_Application_ApprovedAsync(ptin, mobile, mailid, null);
        }
        
        /// <remarks/>
        public void PT_Send_Application_ApprovedAsync(string ptin, string mobile, string mailid, object userState) {
            if ((this.PT_Send_Application_ApprovedOperationCompleted == null)) {
                this.PT_Send_Application_ApprovedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPT_Send_Application_ApprovedOperationCompleted);
            }
            this.InvokeAsync("PT_Send_Application_Approved", new object[] {
                        ptin,
                        mobile,
                        mailid}, this.PT_Send_Application_ApprovedOperationCompleted, userState);
        }
        
        private void OnPT_Send_Application_ApprovedOperationCompleted(object arg) {
            if ((this.PT_Send_Application_ApprovedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PT_Send_Application_ApprovedCompleted(this, new PT_Send_Application_ApprovedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PT_Send_Reset_Password", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PT_Send_Reset_Password(string ptin, string mobile, string mailid) {
            object[] results = this.Invoke("PT_Send_Reset_Password", new object[] {
                        ptin,
                        mobile,
                        mailid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PT_Send_Reset_PasswordAsync(string ptin, string mobile, string mailid) {
            this.PT_Send_Reset_PasswordAsync(ptin, mobile, mailid, null);
        }
        
        /// <remarks/>
        public void PT_Send_Reset_PasswordAsync(string ptin, string mobile, string mailid, object userState) {
            if ((this.PT_Send_Reset_PasswordOperationCompleted == null)) {
                this.PT_Send_Reset_PasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPT_Send_Reset_PasswordOperationCompleted);
            }
            this.InvokeAsync("PT_Send_Reset_Password", new object[] {
                        ptin,
                        mobile,
                        mailid}, this.PT_Send_Reset_PasswordOperationCompleted, userState);
        }
        
        private void OnPT_Send_Reset_PasswordOperationCompleted(object arg) {
            if ((this.PT_Send_Reset_PasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PT_Send_Reset_PasswordCompleted(this, new PT_Send_Reset_PasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PT_Send_ARN_Number", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PT_Send_ARN_Number(string ptin, string mobile, string mailid) {
            object[] results = this.Invoke("PT_Send_ARN_Number", new object[] {
                        ptin,
                        mobile,
                        mailid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PT_Send_ARN_NumberAsync(string ptin, string mobile, string mailid) {
            this.PT_Send_ARN_NumberAsync(ptin, mobile, mailid, null);
        }
        
        /// <remarks/>
        public void PT_Send_ARN_NumberAsync(string ptin, string mobile, string mailid, object userState) {
            if ((this.PT_Send_ARN_NumberOperationCompleted == null)) {
                this.PT_Send_ARN_NumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPT_Send_ARN_NumberOperationCompleted);
            }
            this.InvokeAsync("PT_Send_ARN_Number", new object[] {
                        ptin,
                        mobile,
                        mailid}, this.PT_Send_ARN_NumberOperationCompleted, userState);
        }
        
        private void OnPT_Send_ARN_NumberOperationCompleted(object arg) {
            if ((this.PT_Send_ARN_NumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PT_Send_ARN_NumberCompleted(this, new PT_Send_ARN_NumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PT_Send_Application_Number", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PT_Send_Application_Number(string ptin, string mobile, string mailid) {
            object[] results = this.Invoke("PT_Send_Application_Number", new object[] {
                        ptin,
                        mobile,
                        mailid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PT_Send_Application_NumberAsync(string ptin, string mobile, string mailid) {
            this.PT_Send_Application_NumberAsync(ptin, mobile, mailid, null);
        }
        
        /// <remarks/>
        public void PT_Send_Application_NumberAsync(string ptin, string mobile, string mailid, object userState) {
            if ((this.PT_Send_Application_NumberOperationCompleted == null)) {
                this.PT_Send_Application_NumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPT_Send_Application_NumberOperationCompleted);
            }
            this.InvokeAsync("PT_Send_Application_Number", new object[] {
                        ptin,
                        mobile,
                        mailid}, this.PT_Send_Application_NumberOperationCompleted, userState);
        }
        
        private void OnPT_Send_Application_NumberOperationCompleted(object arg) {
            if ((this.PT_Send_Application_NumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PT_Send_Application_NumberCompleted(this, new PT_Send_Application_NumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PT_Return_Reminder_mail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PT_Return_Reminder_mail(string ptin, string enterprise_name, string filed, string tobefiled, string mailid) {
            object[] results = this.Invoke("PT_Return_Reminder_mail", new object[] {
                        ptin,
                        enterprise_name,
                        filed,
                        tobefiled,
                        mailid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PT_Return_Reminder_mailAsync(string ptin, string enterprise_name, string filed, string tobefiled, string mailid) {
            this.PT_Return_Reminder_mailAsync(ptin, enterprise_name, filed, tobefiled, mailid, null);
        }
        
        /// <remarks/>
        public void PT_Return_Reminder_mailAsync(string ptin, string enterprise_name, string filed, string tobefiled, string mailid, object userState) {
            if ((this.PT_Return_Reminder_mailOperationCompleted == null)) {
                this.PT_Return_Reminder_mailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPT_Return_Reminder_mailOperationCompleted);
            }
            this.InvokeAsync("PT_Return_Reminder_mail", new object[] {
                        ptin,
                        enterprise_name,
                        filed,
                        tobefiled,
                        mailid}, this.PT_Return_Reminder_mailOperationCompleted, userState);
        }
        
        private void OnPT_Return_Reminder_mailOperationCompleted(object arg) {
            if ((this.PT_Return_Reminder_mailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PT_Return_Reminder_mailCompleted(this, new PT_Return_Reminder_mailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Auto_mail_live_test2CompletedEventHandler(object sender, Auto_mail_live_test2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Auto_mail_live_test2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Auto_mail_live_test2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Auto_mailCompletedEventHandler(object sender, Auto_mailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Auto_mailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Auto_mailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ITC_circular_09112022CompletedEventHandler(object sender, ITC_circular_09112022CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ITC_circular_09112022CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ITC_circular_09112022CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void PT_mail_Not_paid_list_AutoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GSTR9c_mailCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void PT_mail_Not_paid_listCompletedEventHandler(object sender, PT_mail_Not_paid_listCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PT_mail_Not_paid_listCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PT_mail_Not_paid_listCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Live_mail_Bulk_for_RupaCompletedEventHandler(object sender, Live_mail_Bulk_for_RupaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Live_mail_Bulk_for_RupaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Live_mail_Bulk_for_RupaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Live_mail_BulkCompletedEventHandler(object sender, Live_mail_BulkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Live_mail_BulkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Live_mail_BulkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void PT_auto_gen_SendmailCompletedEventHandler(object sender, PT_auto_gen_SendmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PT_auto_gen_SendmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PT_auto_gen_SendmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void send_mail_daily_reportCompletedEventHandler(object sender, send_mail_daily_reportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class send_mail_daily_reportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal send_mail_daily_reportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void send_mail_appCompletedEventHandler(object sender, send_mail_appCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class send_mail_appCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal send_mail_appCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void send_mail_ptin_appCompletedEventHandler(object sender, send_mail_ptin_appCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class send_mail_ptin_appCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal send_mail_ptin_appCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void send_mail_Vat_reset_passwordCompletedEventHandler(object sender, send_mail_Vat_reset_passwordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class send_mail_Vat_reset_passwordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal send_mail_Vat_reset_passwordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void send_mail_Vat_Registration_OTPCompletedEventHandler(object sender, send_mail_Vat_Registration_OTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class send_mail_Vat_Registration_OTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal send_mail_Vat_Registration_OTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void send_mail_PT_GST_new_usersCompletedEventHandler(object sender, send_mail_PT_GST_new_usersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class send_mail_PT_GST_new_usersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal send_mail_PT_GST_new_usersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void send_mail_statusCompletedEventHandler(object sender, send_mail_statusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class send_mail_statusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal send_mail_statusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void Auto_mail_liveCompletedEventHandler(object sender, Auto_mail_liveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Auto_mail_liveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Auto_mail_liveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GST_payment_report_dateWiseCompletedEventHandler(object sender, GST_payment_report_dateWiseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GST_payment_report_dateWiseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GST_payment_report_dateWiseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void test_mail_liveCompletedEventHandler(object sender, test_mail_liveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class test_mail_liveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal test_mail_liveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void test_mailCompletedEventHandler(object sender, test_mailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class test_mailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal test_mailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void getpr_mail_service_sent_statusCompletedEventHandler(object sender, getpr_mail_service_sent_statusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getpr_mail_service_sent_statusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getpr_mail_service_sent_statusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void PT_Send_Application_ApprovedCompletedEventHandler(object sender, PT_Send_Application_ApprovedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PT_Send_Application_ApprovedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PT_Send_Application_ApprovedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void PT_Send_Reset_PasswordCompletedEventHandler(object sender, PT_Send_Reset_PasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PT_Send_Reset_PasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PT_Send_Reset_PasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void PT_Send_ARN_NumberCompletedEventHandler(object sender, PT_Send_ARN_NumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PT_Send_ARN_NumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PT_Send_ARN_NumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void PT_Send_Application_NumberCompletedEventHandler(object sender, PT_Send_Application_NumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PT_Send_Application_NumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PT_Send_Application_NumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void PT_Return_Reminder_mailCompletedEventHandler(object sender, PT_Return_Reminder_mailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PT_Return_Reminder_mailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PT_Return_Reminder_mailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591